### ISSUE TITLE
Error saying does not follow values of Hactoberfest on profile

### ISSUE THREAD

**Issue by JIBIN-P** [timdeschryver/hacktoberfest-2019-angular#202]
Hi, My PR was in the maturing phase and suddenly when I checked my profile it started showing me this error. Can you please help me to get it validated by the Hacktoberfest team?
![image](https://user-images.githubusercontent.com/20881214/139595191-7c6d5da7-5a1b-4162-9137-7362ba1e9f8b.png)

**Comment by timdeschryver** [comment]
I didn't really follow this year.
Do you know what I can do to get this resolved?

**Comment by JIBIN-P** [comment]
I am not sure if there is something we can do since it's past Oct 31, but we can add trying the label Hacktoberfest in the PR.
https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/197
https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/198
https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/199
https://github.com/timdeschryver/hacktoberfest-2019-angular/pull/200

**Comment by timdeschryver** [comment]
@JIBIN-P done.
